## Color palette

# yellows:  dba355 d8a038 d8bd36 edd17d
# greens:   92ef92 6bbf3b 1cef5c 75b72d 9fea8f c6e84e c1f45a b8d613 fcf0b5 
# reds:     dd362a
# blues:    5b91c6 2a7d93 0bb1ed
# pinks:    bf0f73
# oranges:  ba500e ce8048
# teals:    40c491
#
# Tailwind CSS colors: https://tailwindcss.com/docs/customizing-colors/

###
### Special magic GitHub labels
###
- name: "good first issue"
  color: 7057ff
  description: "Good for newcomers"
- name: "help wanted"
  color: 008672
  description: "Extra attention is needed"

###
### Areas
###
- name: area/*
  color: 0bb1ed
  description: "Area: Generic (will unfold later)"

###
### Kinds
###
- name: kind/bug
  color: c92712
  description: "Kind: Bug"
- name: kind/problem
  color: c92712
  description: "Kind: Problem"
- name: kind/investigation
  color: fcf0b5
  description: "Kind: Investigation"
- name: kind/chore
  color: fcf0b5
  description: "Kind: Chore"
- name: kind/feature
  color: fcf0b5
  description: "Kind: Feature"
- name: kind/improvement
  color: fcf0b5
  description: "Kind: Improvement"
- name: kind/test-scenario
  color: fcf0b5
  description: "Kind: Test Scenario"
- name: kind/tracking-issue
  color: fcf0b5
  description: "Kind: Tracking Issue"
- name: kind/question
  color: fcf0b5
  description: "Kind: Question"
- name: kind/enhancement
  color: fcf0b5
  description: "Kind: Enhancement"
- name: kind/discussion
  color: fcf0b5
  description: "Kind: Discussion"
- name: kind/spike
  color: fcf0b5
  description: "Kind: Spike"
- name: kind/system-process
  color: fcf0b5
  description: "Kind: System Process"

###
### Difficulties
###
- name: dif/trivial
  color: b2b7ff
  description: "Difficulty: Trivial"
- name: dif/easy
  color: 7886d7
  description: "Difficulty: Easy"
- name: dif/medium
  color: 6574cd
  description: "Difficulty: Medium"
- name: dif/hard
  color: 5661b3
  description: "Difficulty: Hard"
- name: dif/expert
  color: 2f365f
  description: "Difficulty: Expert"

###
### Efforts
###
- name: effort/minutes
  color: e8fffe
  description: "Effort: Minutes"
- name: effort/hours
  color: a0f0ed
  description: "Effort: One or Multiple Hours."
- name: effort/day
  color: 64d5ca
  description: "Effort: One Day."
- name: effort/days
  color: 4dc0b5
  description: "Effort: Multiple Days."
- name: effort/week
  color: 38a89d
  description: "Effort: One Week."
- name: effort/weeks
  color: 20504f
  description: "Effort: Multiple Weeks."  

###
### Discomfort Factor
###
- name: discomfort-factor/10
  color: c53030
  description: "Discomfort factor: I wake up in the middle of the night with nightmares, sweats, and chills."
- name: discomfort-factor/9
  color: e53e3e
  description: "Discomfort factor: Wakes me up in the middle of the night, but if I breathe deep, I can sleep again."
- name: discomfort-factor/8
  color: f56565
  description: "Discomfort factor: I touched my eyes after picking up a Jalapeño (10,000 SHU)."
- name: discomfort-factor/7
  color: dd6b20
  description: "Discomfort factor: Sitting next to a sweaty gentleman in a transatlantic flight."
- name: discomfort-factor/6
  color: ed8936
  description: "Discomfort factor: Agonizing smalltalk."
- name: discomfort-factor/5
  color: f6ad55
  description: "Discomfort factor: Watching tourists wear white socks with flip-flops."
- name: discomfort-factor/4
  color: ecc94b
  description: "Discomfort factor: An itchy jumper label the entire night."
- name: discomfort-factor/3
  color: f6e05e
  description: "Discomfort factor: A pebble in my shoe."
- name: discomfort-factor/2
  color: faf089
  description: "Discomfort factor: A sneeze that just won't come out."
- name: discomfort-factor/1
  color: c6f6d5
  description: "Discomfort factor: Opening a can with a supposedly 'easy open lid' whose ring has snapped."
- name: discomfort-factor/0
  color: f0fff4
  description: "Discomfort factor: Don't worry, chill, we're cool!"
  
###
### Priorities
###
- name: P0
  color: dd362a
  description: "P0: Critical. This is a blocker. Drop everything else."
- name: P1
  color: ce8048
  description: "P1: Must be fixed."
- name: P2
  color: dbd81a
  description: "P2: Should be fixed."
- name: P3
  color: 9fea8f
  description: "P3: Might get fixed."

###
### Hints
###
- name: hint/good-first-issue
  color: 0623cc
  description: "Hint: Good First Issue"
- name: hint/needs-contributor
  color: 0623cc
  description: "Hint: Needs Contributor"
- name: hint/needs-participation
  color: 0623cc
  description: "Hint: Needs Participation"
- name: hint/needs-decision
  color: 0623cc
  description: "Hint: Needs Decision"
- name: hint/needs-triage
  color: 0623cc
  description: "Hint: Needs Triage"
- name: hint/needs-analysis
  color: 0623cc
  description: "Hint: Needs Analysis"
- name: hint/needs-author-input
  color: 0623cc
  description: "Hint: Needs Author Input"
- name: hint/needs-team-input
  color: 0623cc
  description: "Hint: Needs Team Input"
- name: hint/needs-community-input
  color: 0623cc
  description: "Hint: Needs Community Input"
- name: hint/needs-review
  color: 0623cc
  description: "Hint: Needs Review"
- name: hint/needs-help
  color: 0623cc
  description: "Hint: Needs Help"  
- name: hint/desc-outdated
  color: 0623cc
  description: "Hint: Description outdated"  

###
### Statuses
###
- name: status/done
  color: edb3a6
  description: "Status: Done"
- name: status/approved-waiting
  color: edb3a6
  description: "Status: Approved and Awaiting Merge"
- name: status/changes-requested
  color: edb3a6
  description: "Status: Changes Requested in Review"
- name: status/awaiting-review
  color: edb3a6
  description: "Status: Waiting for Review"
- name: status/deferred
  color: edb3a6
  description: "Status: Deferred"
- name: status/in-progress
  color: edb3a6
  description: "Status: In Progress"
- name: status/blocked
  color: edb3a6
  description: "Status: Blocked"
- name: status/inactive
  color: edb3a6
  description: "Status: Inactive"
- name: status/waiting
  color: edb3a6
  description: "Status: Waiting"
- name: status/rotten
  color: edb3a6
  description: "Status: Rotten"  
- name: status/discarded
  color: a0aec0
  description: "Status: Discarded / Won't fix"  
