coverage:
  status:
    patch: off
    project:
      tools-and-tests:
        target: auto
        threshold: 0.5%
        informational: true
        paths:
          - "testplans"
          - "tools"
          - "system"
          - "snap"
          - "lotuspond"
          - "conformance"
          - "scripts"
          - "gen"
          - "build"
      markets: 
        target: auto
        threshold: 0.5%
        informational: false        
        paths: 
          - "markets"
          - "paychmgr"
      miner: 
        target: auto
        threshold: 1%
        informational: false       
        paths: 
          - "miner"
          - "storage"
      chain:
        target: auto
        threshold: 0.5%
        informational: false
        paths:
          - "chain"
      node: 
        target: auto
        threshold: 0.5%
        informational: false
        paths: 
          - "node"
          - "blockstore"
          - "metrics"
          - "lib"
          - "genesis"
          - "gateway"
          - "api"
          - "journal"
      cli: 
        target: auto
        threshold: 0.5%
        informational: true
        paths: 
          - "cli"
          - "cmd"
