linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - goimports
    - misspell
    - goconst
    - golint
    - errcheck
    - gosec
    - unconvert
    - staticcheck
    - varcheck
    - structcheck
    - deadcode
    - scopelint


issues:
  exclude:
    - "func name will be used as test\\.Test.* by other packages, and that stutters; consider calling this"
    - "Potential file inclusion via variable"
    - "should have( a package)? comment"
    - "Error return value of `logging.SetLogLevel` is not checked"

  exclude-use-default: false
  exclude-rules:
    - path: lotuspond
      linters:
        - errcheck

    - path: node/modules/lp2p
      linters:
        - golint

    - path: build/params_.*\.go
      linters:
        - golint
          
    - path: api/apistruct/struct.go
      linters:
        - golint

    - path: .*_test.go
      linters:
        - gosec

linters-settings:
  goconst:
    min-occurrences: 6
