version: "2"
linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused
  exclusions:
    generated: lax
    rules:
      - linters:
          - gosec
        path: .*_test.go
      - linters:
          - gosec
        path: chain/vectors/gen/.*
      - linters:
          - gosec
        path: cmd/lotus-bench/.*
      - path: (.+)\.go$
        text: '^G101: Potential hardcoded credentials'
      - path: (.+)\.go$
        text: '^G108: Profiling endpoint is automatically exposed on /debug/pprof'
      - path: (.+)\.go$
        text: '^G204: Subprocess launched with (variable|a potential tainted input or cmd arguments)'
      - path: (.+)\.go$
        text: '^G301: Expect directory permissions to be 0750 or less'
      - path: (.+)\.go$
        text: '^G302: Expect file permissions to be 0600 or less'
      - path: (.+)\.go$
        text: '^G304: Potential file inclusion via variable'
      - path: (.+)\.go$
        text: '^G306: Expect WriteFile permissions to be 0600 or less'
      - path: (.+)\.go$
        text: '^G404: Use of weak random number generator'
      - path: (.+)\.go$
        text: '^SA1019: xerrors.* is deprecated: As of Go 1.13, use errors'
      - path: (.+)\.go$
        text: '^blank-imports: a blank import should be only in a main or test package, or have a comment justifying it'
      - path: (.+)\.go$
        text: '^dot-imports: should not use dot imports'
      - path: (.+)\.go$
        text: '^exported: (func|type) name will be used as [^\s]+ by other packages, and that stutters; consider calling this \w+'
      - path: (.+)\.go$
        text: '^exported: comment on exported (const|var) [^\s]+ should be of the form "\w+ ..."'
      - path: (.+)\.go$
        text: '^exported: exported (const|function|method|type|var) [^\s]+ should have comment (\(or a comment on this block\) )?or be unexported'
      - path: (.+)\.go$
        text: '^indent-error-flow: if block ends with a return statement, so drop this else and outdent its block \(move short variable declaration to its own line if necessary\)'
      - path: (.+)\.go$
        text: '^package-comments: package comment should be of the form "Package \w+ ..."'
      - path: (.+)\.go$
        text: '^package-comments: should have a package comment'
      - path: (.+)\.go$
        text: '^unexported-return: exported func \w+ returns unexported type [^\s]+, which can be annoying to use'
      - path: (.+)\.go$
        text: '^unused-parameter: parameter ''\w+'' seems to be unused, consider removing or renaming it as _'
      - path: (.+)\.go$
        text: '^var-naming: (const|func|type|var|struct field|(method|func|interface method) parameter) [A-Z]\w+ should be'
      - path: (.+)\.go$
        text: '^var-naming: (method|range var) \w*(Api|Http|Id|Rpc|Url)[^\s]* should be \w*(API|HTTP|ID|RPC|URL)'
      - path: (.+)\.go$
        text: '^var-naming: don''t use underscores in Go names'
      - path: (.+)\.go$
        text: '^var-naming: don''t use ALL_CAPS in Go names; use CamelCase'
    paths:
      - chain/types/testdata/.*
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - chain/types/testdata/.*
