# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json

version: 2
project_name: "{{ .Env.PROJECT_NAME }}"
universal_binaries:
  - id: lotus
    replace: true
    name_template: lotus
  - id: lotus-miner
    replace: true
    name_template: lotus-miner
  - id: lotus-worker
    replace: true
    name_template: lotus-worker
builds:
  - id: lotus
    binary: lotus
    builder: prebuilt
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    ignore:
      - goos: linux
        goarch: arm64
    prebuilt:
      path: "{{ .Env.GITHUB_WORKSPACE }}/{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/lotus"
    skip: true
  - id: lotus-miner
    binary: lotus-miner
    builder: prebuilt
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    ignore:
      - goos: linux
        goarch: arm64
    prebuilt:
      path: "{{ .Env.GITHUB_WORKSPACE }}/{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/lotus-miner"
    skip: true
  - id: lotus-worker
    binary: lotus-worker
    builder: prebuilt
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    ignore:
      - goos: linux
        goarch: arm64
    prebuilt:
      path: "{{ .Env.GITHUB_WORKSPACE }}/{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/lotus-worker"
    skip: true
archives:
  - id: primary
    format: tar.gz
    wrap_in_directory: true
    name_template: "{{ .Env.PROJECT_NAME }}_v{{ .Env.VERSION }}_{{ .Os }}_{{ .Arch }}"
    files:
      # this is a dumb but required hack so it doesn't include the default files
      # https://github.com/goreleaser/goreleaser/issues/602
      - _n_o_n_e_*
release:
  github:
    owner: filecoin-project
    name: lotus
  draft: true
  header: "{{ .Env.HEADER }}"
  make_latest: "{{ .Env.IS_LATEST }}"
  name_template: "{{ .Env.TAG }}"
  prerelease: "{{ .Env.IS_PRERELEASE }}"
  replace_existing_artifacts: true
  replace_existing_draft: false
  tag: "{{ .Env.TAG }}"
  target_commitish: "{{ .Env.TARGET_COMMITISH }}"
brews:
  - name: "{{ .Env.PROJECT_NAME }}"
    repository:
      owner: filecoin-project
      name: homebrew-lotus
      branch: master
    ids:
      - primary
    install: ""
    test: ""
    directory: Formula
    homepage: "https://filecoin.io"
    description: "A homebrew cask for installing filecoin-project/lotus on MacOS"
    license: MIT
    skip_upload: true
    dependencies:
      - name: hwloc
    commit_msg_template: "Brew formula update for {{ .Env.PROJECT_NAME }} version {{ .Env.TAG }}"
# produced manually so we can include cid checksums
checksum:
  disable: true
snapshot:
  name_template: "{{ .Env.PROJECT_NAME }}_v{{ .Env.VERSION }}"
