project_name: lotus

universal_binaries:
  - id: lotus
    replace: true
    name_template: lotus
  - id: lotus-miner
    replace: true
    name_template: lotus-miner
  - id: lotus-worker
    replace: true
    name_template: lotus-worker

builds:
  - id: lotus
    binary: lotus
    builder: prebuilt
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    ignore:
      - goos: linux
        goarch: arm64
    prebuilt:
      path: /tmp/workspace/{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/lotus
  - id: lotus-miner
    binary: lotus-miner
    builder: prebuilt
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    ignore:
      - goos: linux
        goarch: arm64
    prebuilt:
      path: /tmp/workspace/{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/lotus-miner
  - id: lotus-worker
    binary: lotus-worker
    builder: prebuilt
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    ignore:
      - goos: linux
        goarch: arm64
    prebuilt:
      path: /tmp/workspace/{{ .Os }}_{{ .Arch }}{{ with .Amd64 }}_{{ . }}{{ end }}/lotus-worker

archives:
  - id: primary
    format: tar.gz
    wrap_in_directory: true
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      # this is a dumb but required hack so it doesn't include the default files
      # https://github.com/goreleaser/goreleaser/issues/602
      - _n_o_n_e_*

release:
  github:
    owner: filecoin-project
    name: lotus
  prerelease: auto
  name_template: "v{{.Version}}"

brews:
  - tap:
      owner: filecoin-project
      name: homebrew-lotus
      branch: master
    ids:
      - primary
    install: |
      bin.install "lotus"
      bin.install "lotus-miner"
      bin.install "lotus-worker"
    test: |
      system "#{bin}/lotus --version"
      system "#{bin}/lotus-miner --version"
      system "#{bin}/lotus-worker --version"
    folder: Formula
    homepage: "https://filecoin.io"
    description: "A homebrew cask for installing filecoin-project/lotus on MacOS"
    license: MIT
    skip_upload: auto
    dependencies:
      - name: hwloc

# produced manually so we can include cid checksums
checksum:
  disable: true

snapshot:
  name_template: "{{ .Version }}"
