name: Start YugabyteDB
description: Install Yugabyte Database for Filecoin Lotus

runs:
  using: composite
  steps:
    - run: docker run --rm --name yugabyte -d -p 5433:5433 yugabytedb/yugabyte:2.18.0.0-b65 bin/yugabyted start --daemon=false
      shell: bash
    - run: |
        while true; do
          status=$(docker exec yugabyte bin/yugabyted status);
          echo $status;
          echo $status | grep Running && break;
          sleep 1;
        done
      shell: bash
