version: '3'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "18086:8086"
    environment:
      - INFLUXDB_DB=lotus
    volumes:
      - influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "13000:3000"
    links:
      - influxdb
    volumes:
      - grafana:/var/lib/grafana

volumes:
  influxdb:
  grafana:
