{
 "title": "F3 Dashboard",
 "tags": [
  "f3",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "GPBFT Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest Stored Cert Instance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(f3_certstore_latest_instance) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Rounds",
   "type": "stat",
   "description": "The maximum number of rounds it took for an instance to complete over the time period.",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum(f3_gpbft_round_histogram_bucket) by (le))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Epoch Finalized",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(f3_certstore_latest_finalized_epoch) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Head Divergence",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (f3_head_diverged_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Instance and Round",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(f3_gpbft_current_instance)", "legendFormat": "Instance" },
    { "expr": "max(f3_gpbft_current_round)", "legendFormat": "Round" }
   ]
  },
  {
   "title": "Timeouts Rate",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*rate(f3_gpbft_timeouts_triggered[$__rate_interval]) / \n(rate(f3_gpbft_timeouts_triggered[$__rate_interval]) + rate(f3_gpbft_transitions_succeeded[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPBFT Instance Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(f3_gpbft_instance_duration_bucket[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "GPBFT Instance Duration Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(f3_gpbft_instance_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(f3_gpbft_instance_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(f3_gpbft_instance_duration_bucket[$__rate_interval])) by (le))",
     "legendFormat": "99th percentile"
    }
   ]
  },
  {
   "title": "GPBFT Instance Completion Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "avg(rate(f3_gpbft_instances_completed_total[$__rate_interval]))",
     "legendFormat": "Instances Completed"
    }
   ]
  },
  {
   "title": "GPBFT Rebroadcast Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "avg (sum by(instance)(rate(f3_gpbft_rebroadcast_counter_total[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors by Kind",
   "type": "timeseries",
   "description": "GPBFT Error Rate by kind per instance",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(err)(rate(f3_gpbft_error_counter_total[1m]))",
     "legendFormat": "{{err}}"
    }
   ]
  },
  {
   "title": "Phase transition rate by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "sum by(phase) (increase(f3_gpbft_phase_counter_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tipsets Per Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "avg(f3_certstore_tipsets_per_instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Encoding Performance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(f3_internal_encoding_time_seconds_bucket[$__rate_interval])) by (le,action,codec))",
     "legendFormat": "50th {{codec}}/{{action}} "
    }
   ]
  },
  { "title": "Lotus Go Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "avg(sum by (instance)(go_goroutines))",
     "legendFormat": "Go Routines"
    }
   ]
  },
  {
   "title": "Heap Object Allocation Rate",
   "type": "timeseries",
   "description": "Average rate of heap object allocation, across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(sum(rate(go_memstats_mallocs_total[$__rate_interval])) by (instance))",
     "legendFormat": "Heap Allocation Rate"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.25\"} * 1000",
     "legendFormat": "25th Percentile"
    },
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.5\"} * 1000",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "go_gc_duration_seconds{quantile=\"0.75\"} * 1000",
     "legendFormat": "75th Percentile"
    }
   ]
  },
  {
   "title": "CPU Usage & Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - sum(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) / sum(rate(node_cpu_seconds_total[$__rate_interval])))",
     "legendFormat": "CPU Usage"
    },
    { "expr": "node_load1", "legendFormat": "Load Average (1m)" }
   ]
  },
  {
   "title": "Libp2p Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "avg by(protocol) (rate(lotus_libp2p_bandwidth_bytes_total{direction=\"inbound\"}[2m])) * -1 != 0",
     "legendFormat": "rx:{{protocol}}"
    },
    {
     "expr": "avg by(protocol) (rate(lotus_libp2p_bandwidth_bytes_total{direction=\"outbound\"}[2m])) != 0",
     "legendFormat": "tx:{{protocol}}"
    }
   ]
  }
 ]
}