name: Export Circle Env
description: Export CircleCI environment variables for Filecoin Lotus

runs:
  using: composite
  steps:
    - run: |
        if [[ "$GITHUB_REF" == refs/tags/* ]]; then
          echo "CIRCLE_TAG=${GITHUB_REF#refs/tags/}" | tee -a $GITHUB_ENV
        fi
        echo "CIRCLE_PROJECT_USERNAME=$GITHUB_REPOSITORY_OWNER" | tee -a $GITHUB_ENV
        echo "CIRCLE_PROJECT_REPONAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" | tee -a $GITHUB_ENV
        echo "CIRCLE_SHA1=$GITHUB_SHA" | tee -a $GITHUB_ENV
      shell: bash
