name: "M1 Bug Report For Non Deal Making Issue"
description: "File a bug report around non deal making issue for the M1 releases"
labels: [need/triage, kind/bug, M1-release]
body:
- type: checkboxes
  id: checklist
  attributes:
    label: Checklist
    description: Please check off the following boxes before continuing to file a bug report!
    options:
      - label: This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
        required: true
      - label: I **am** reporting a bug w.r.t one of the [M1 tags](https://github.com/filecoin-project/lotus/discussions/6852#discussioncomment-1043951). If not, choose another issue option [here](https://github.com/filecoin-project/lotus/issues/new/choose).
        required: true
      - label: I am **not** reporting a bug around deal making. If yes, create a [M1 Bug Report For Deal Making](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fbug%2CM1-release&template=m1_bug_report_deal.yml).
        required: true
      - label: I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
        required: true
- type: dropdown 
  id: component-and-area
  validations:
    required: true
  attributes:
    label: Lotus component
    description: Please select the lotus component you are filing a bug for
    options:
    - lotus daemon - chain sync **with** splitstore enabled
    - lotus daemon - chain sync **without** splitstore enabled
    - lotus miner - mining and block production
    - lotus miner/worker - sealing
    - lotus miner - proving(WindowPoSt)
    - lotus client
    - lotus JSON-RPC API
    - lotus message management (mpool)
    - Other
- type: textarea
  id: version
  attributes:
    label: Lotus Tag and  Version
    description: Enter the  lotus tag, output of `lotus version` and `lotus-miner version`.
  validations:
    reuiqred: true
- type: textarea
  id: Description
  attributes:
    label: Describe the Bug
    description: |
      This is where you get to tell us what went wrong, when doing so, please try to provide a clear and concise description of the bug with all related information:
      * What you were doding when you experienced the bug?
      * Any *error* messages you saw, *where* you saw them, and what you believe may have caused them (if you have any ideas).
      * What is the expected behaviour?
      * For sealing issues, include the output of `lotus-miner sectors status --log <sectorId>` for the failed sector(s).
      * For proving issues, include the output of `lotus-miner proving` info.
    render: bash
  validations:
    required: true
- type: textarea
  id: extraInfo
  attributes:
    label: Logging Information
    description: |
      Please provide debug logs of the problem, remember you can get set log level control for:
      * lotus: use `lotus log list` to get all log systems available and set level by `lotus log set-level`. An example can be found [here](https://docs.filecoin.io/get-started/lotus/configuration-and-advanced-usage/#log-level-control).
      * lotus-miner:`lotus-miner log list` to get all log systems available and set level by `lotus-miner log set-level
      If you don't provide detailed logs when you raise the issue it will almost certainly be the first request I make before furthur diagnosing the problem.
    render: bash
  validations:
    required: true
- type: textarea
  id: RepoSteps
  attributes:
    label: Repo Steps
    description: "Steps to reproduce the behavior"
    value: |
      1. Run '...'
      2. Do '...'
      3. See error '...'
      ...
    render: bash
  validations:
    required: false