#!/bin/sh
set -e

case "$1" in
    configure)
        # Reload systemd after installation or upgrade
        systemctl daemon-reload

        if [ -z "$2" ]; then
            # This is an initial installation
            systemctl enable curio.service
            echo "CURIO_LAYERS=gui,post\nCURIO_DB=postgres://yugabyte:yugabyte@yugabyte/yugabyte\n" >/etc/curio.env
            echo "setup /etc/curio.env then run: systemctl start curio.service"
        else
            # This is an upgrade
            systemctl restart curio.service
        fi
    ;;
esac

exit 0
