ARG GO_VERSION=1.14.2

FROM golang:${GO_VERSION}-buster

RUN apt-get update && apt-get install -y ca-certificates llvm clang mesa-opencl-icd ocl-icd-opencl-dev jq gcc git bzr pkg-config

ARG LOTUS_VERSION

RUN git clone https://github.com/filecoin-project/lotus.git /lotus && cd /lotus && git checkout ${LOTUS_VERSION} && git submodule update --init

RUN cd /lotus/extern/filecoin-ffi \
    && make \
    && mkdir /tmp/filecoin-ffi \
    && cp -R /lotus/extern/filecoin-ffi /tmp
