{
 "title": "Project Oni - Baseline test",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "myinterval", "query": "10s,100s" },
   { "name": "runid", "query": "SHOW TAG VALUES WITH KEY = run" }
  ]
 },
 "panels": [
  {
   "title": "message/received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "message/received",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "message/success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "message/success",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "chain/node_height",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "chain/node_height",
     "select": [
      [
       { "params": [ "last" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "peer/count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "peer/count",
     "select": [
      [
       { "params": [ "last" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "block/received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block/received",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "block/success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_instance",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "block/success",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "mined blocks from testplan",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_miner ($tag_run)",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "run" ], "type": "tag" },
      { "params": [ "miner" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.block.mine.counter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runid$/" }
     ]
    },
    {
     "alias": "all ($tag_run)",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "run" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.block.mine.counter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runid$/" }
     ]
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "find data",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "find-data - 95% max",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "run" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.find-data.histogram",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runid$/" }
     ]
    }
   ]
  },
  {
   "title": "send data to ; got retrieve offers from",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "send-data-to - $tag_miner ($tag_run)",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "miner" ], "type": "tag" },
      { "params": [ "run" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.send-data-to.counter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runid$/" }
     ]
    },
    {
     "alias": "find-data.offer - $tag_miner ($tag_run)",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "miner" ], "type": "tag" },
      { "params": [ "run" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.find-data.offer.counter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runid$/" }
     ]
    }
   ]
  },
  { "title": "Deals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "started -> sealed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "deal.sealed - 95% max",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "run" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.deal.sealed.histogram",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runid$/" }
     ]
    }
   ]
  },
  {
   "title": "started -> retrieved",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "deal.retrieved - 95% max ($tag_run)",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "run" ], "type": "tag" },
      { "params": [ "run" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.deal.retrieved.histogram",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runid$/" }
     ]
    },
    {
     "alias": "deal.retrieved - min ($tag_run)",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "run" ], "type": "tag" },
      { "params": [ "run" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.deal.retrieved.histogram",
     "select": [
      [
       { "params": [ "min" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runid$/" }
     ]
    }
   ]
  },
  {
   "title": "started -> sealed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "deal.sealed - count",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "run" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.deal.sealed.histogram",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runid$/" }
     ]
    }
   ]
  },
  {
   "title": "started -> retrieved",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "deal.retrieved - count",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "run" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.deal.retrieved.histogram",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "run", "operator": "=~", "value": "/^$runid$/" }
     ]
    }
   ]
  }
 ]
}