{
 "title": "Project Oni - Baseline test",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "myinterval", "query": "10s,100s" }
  ]
 },
 "panels": [
  { "title": "Params", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "block delay",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.miner.block-delay.gauge",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "mined blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "run" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.miner.mine.counter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "find data",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "run" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.find-data.histogram",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "data offers",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.find-data.offer.t0101.counter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.find-data.offer.t0102.counter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.find-data.offer.t0103.counter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.find-data.offer.t0104.counter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "run" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.find-data.offer.counter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Deals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "started -> sealed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "run" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.deal.sealed.histogram",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "started -> retrieved",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "run" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "diagnostics.deal.retrieved.histogram",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}