name: Only Markdown Changed
description: Check whether every changed file in this PR has the .md extension.

inputs:
  github_token:
    description: GitHub token (to fetch the diff)
    required: true

outputs:
  only_markdown_changes:
    description: 'True if every changed file has the .md extension'
    value: ${{ steps.check.outputs.only_markdown_changes }}

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: List changed files
      id: diff
      shell: bash
      run: |
        BASE=$(git merge-base origin/${{ github.event.pull_request.base.ref }} HEAD)
        git diff --name-only $BASE HEAD > changed.txt
        echo "files=$(paste -sd ',' changed.txt)" >> $GITHUB_OUTPUT

    - name: Determine if only .md files changed
      id: check
      shell: bash
      run: |
        nonmd=$(grep -vE '\.md$' changed.txt || true)
        if [ -z "$nonmd" ]; then
          echo "only_markdown_changes=true" >> $GITHUB_OUTPUT
        else
          echo "only_markdown_changes=false" >> $GITHUB_OUTPUT
        fi
