sequenceDiagram

  participant Requestor
  participant ReqDT as Data Transfer Module (Requestor)
  participant ReqSC as Scheduler (Requestor)
  participant ReqGS as Graphsync (Requestor)
  participant ResGS as Graphsync (Requestor)
  participant ResSC as Scheduler (Requestor)
  participant ResDT as Data Transfer Module (Responder)
  participant Responder

  Note over Requestor: Likely A Client
  Note over Responder: Likely A Miner

  Requestor ->> ReqDT : Initiate Push
  ReqDT ->> ReqSC : Schedule Transfer
  ReqDT ->> ResDT : Send Data Transfer Request
  ResDT ->> Responder : Validate Push Request
  Responder ->> ResDT : Push Request validated
  ResDT ->> ResSC : Schedule Transfer
  ResSC ->> ResGS : Make Graphsync Request
  ResGS ->> ReqGS : Send Graphsync Request
  ReqGS ->> ReqSC : Verify Transfer Scheduled
  ReqSC ->> ReqGS : Request is scheduled
  ReqGS ->> ResGS : Send Response
  ResGS ->> ResSC : Response Progress (to end)
  ResSC ->> ResDT : Request Complete
  ResDT ->> Responder : Request Completed (if listening)
