sequenceDiagram
  participant PMC as PaymentChannel (Client)
  participant RetrievalClient
  participant DTC as Data Transfer (Client)
  participant DTM as Data Transfer (Provider)
  participant RetrievalProvider
  participant PMM as PaymentChannel (Provider)
  participant StorageMiner

  opt Querying
    RetrievalClient ->>+ RetrievalProvider: NewRetrievalQuery(RetreivalQuery)
    RetrievalProvider -->>- RetrievalClient: RetrievalQueryResponse
  end

  RetrievalClient ->>+ RetrievalClient: RetrievePiece(PieceID)      
  loop PieceRetrieval
    RetrievalClient ->>+ RetrievalProvider: NewRetrievalDealProposal(RetrievalDealProposal)
    RetrievalProvider -->> RetrievalProvider: AcceptRetrievalDealProposal(RetrievalDealPropsal)
    RetrievalProvider ->>+ PMM: OpenPaymenChannel
    PMM -->>- RetrievalProvider: paymentChannel
    RetrievalProvider -->>- RetrievalClient: NewPaymentChannel
    RetrievalClient ->>+ PMC: AddFunds
    PMC -->>- RetrievalClient: fundsAdded
    RetrievalClient ->> DTC: OpenPartialPullRequest(StorageProvider.Address, Voucher(PaymentChannel), PieceID, Selector)
    DTC ->>+ DTM: OpenPartialPullRequest
    DTM ->>+ RetrievalProvider: ValidateTransfer(Voucher)
    RetrievalProvider ->>+ PMM: VerifyPaymentChannel(PaymentChannel)
    PMM -->>- RetrievalProvider: paymentChannelVerified
    RetrievalProvider ->>+ StorageMiner: UnsealSector
    StorageMiner -->>- RetrievalProvider: sectorUnsealed
    RetrievalProvider -->>- DTM: tranferValidated
    DTM -->>- DTC: Transfer Accepted
    DTC ->>+ DTM: StartTransfer
    DTM -->>- DTC: Send Data
    DTC ->> RetrievalClient: Transfer Complete (via listener)
    RetrievalClient ->> PMC: CloseDeal
  end
  RetrievalClient -->>- RetrievalClient: pieceTransferred