sequenceDiagram
  participant SMAC as StorageMarketActor (Client)
  participant StorageClient
  participant DTC as Data Transfer (Client)
  participant DTM as Data Transfer (Provider)
  participant StorageProvider
  participant SMAM as StorageMarketActor (Provider)
  participant StorageMiner

  opt ClientSetup
    StorageClient ->> SMAC: RegisterParticipant(TokenAmount)
    StorageClient ->> SMAC: AddBalance(TokenAmount)
    StorageClient ->> SMAC: WithdrawBalance(TokenAmount)
    StorageClient ->>+ SMAC: CheckLockedBalance(Address)
    SMAC -->>- StorageClient: TokenAmount
  end

  opt ProviderSetup
    StorageProvider ->> SMAM: RegisterParticipant(TokenAmount)
    StorageProvider ->> SMAM: AddBalance(TokenAmount)
    StorageProvider ->> SMAM: WithdrawBalance(TokenAmount)
    StorageProvider ->+ SMAM: CheckLockedBalance(Address)
    SMAM -->>- StorageProvider: TokenAmount
    StorageProvider ->> DTM: RegisterListener
  end

  StorageClient -->>+ StorageProvider: NewStorageDealProposal(StorageDealProposal)
  StorageProvider ->>+ SMAM: VerifyBalance(StorageMarketParticipant1)
  SMAM -->>- StorageProvider: balance
  StorageProvider ->> StorageProvider: SignStorageDealProposal(StorageDealProposal)
  StorageProvider -->- StorageClient: NewStorageDeal(StorageDeal)
  StorageProvider ->> SMAM: PublishStorageDeal(StorageDeal)
  StorageClient ->> SMAC: PublishStorageDeal(StorageDeal)

  StorageClient ->>+ SMAC: VerifyStorageDeal(StorageDeal)
  SMAC -->>- StorageClient: storageDealVerified
  StorageClient ->> DTC: OpenPushRequest(StorageProvider.Address, Voucher(StorageDealID), PieceID)
  DTC ->>+ DTM: OpenPushRequest
  DTM ->>+ StorageProvider: ValidateTransfer(Voucher)
  StorageProvider ->>+ SMAM: VerifyStorageDeal(StorageDeal)
  SMAM -->>- StorageProvider: storageDealVerified
  StorageProvider -->>- DTM: DealValidated
  DTM -->>- DTC: Start transfer
  DTC ->> DTM: Send Data
  DTM ->> StorageProvider: Transfer Complete (via listener)
  StorageProvider ->>+ SMAM: UpdateStorageDeal
  SMAM -->>- StorageProvider: storageDealUpdated
  StorageProvider ->> StorageMiner: HandleStorageDeal(Deal)
