export default {
  "filecoin/1.0/AccountActor": [
    "Send",
    "Constructor",
    "GetAddress",
  ],
  "filecoin/1.0/StoragePowerActor": [
    "Send",
    "Constructor",
    "CreateStorageMiner",
    "SlashConsensusFault",
    "UpdateStorage",
    "GetTotalStorage",
    "PowerLookup",
    "IsMiner",
    "StorageCollateralForSize"
  ],
  "filecoin/1.0/StorageMarketActor": [
    "Send",
    "Constructor",
    "WithdrawBalance",
    "AddBalance",
    "CheckLockedBalance",
    "PublishStorageDeals",
    "HandleCronAction",
    "SettleExpiredDeals",
    "ProcessStorageDealsPayment",
    "SlashStorageDealCollateral",
    "GetLastExpirationFromDealIDs",
    "ActivateStorageDeals",
  ],
  "filecoin/1.0/StorageMinerActor": [
    "Send",
    "Constructor",
    "CommitSector",
    "SubmitPost",
    "SlashStorageFault",
    "GetCurrentProvingSet",
    "ArbitrateDeal",
    "DePledge",
    "GetOwner",
    "GetWorkerAddr",
    "GetPower",
    "GetPeerID",
    "GetSectorSize",
    "UpdatePeerID",
    "ChangeWorker",
    "IsSlashed",
    "IsLate",
    "PaymentVerifyInclusion",
    "PaymentVerifySector",
  ],
  "filecoin/1.0/MultisigActor": [
    "Send",
    "Constructor",
    "Propose",
    "Approve",
    "Cancel",
    "ClearCompleted",
    "AddSigner",
    "RemoveSigner",
    "SwapSigner",
    "ChangeRequirement",
  ],
  "filecoin/1.0/InitActor": [
    "Send",
    "Constructor",
    "Exec",
    "GetIdForAddress"
  ],
  "filecoin/1.0/PaymentChannelActor": [
    "Send",
    "Constructor",
    "UpdateChannelState",
    "Close",
    "Collect",
  ],
}