name: Build

on:
  pull_request:
  push:
    branches:
      - master
      - release/*
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  skippable:
    name: Detect skippable changes
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    outputs:
      skip: ${{ steps.skippable.outputs.skip }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          sparse-checkout: .github/actions
      - id: skippable
        uses: ./.github/actions/detect-skippable-changes
        with:
          paths: binaries
  build:
    name: Build
    needs: [skippable]
    if: ${{ needs.skippable.outputs.skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - uses: ./.github/actions/install-system-dependencies
      - uses: ./.github/actions/install-go
      - run: make deps lotus
