name: Changelog

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - ready_for_review
    paths:
      - '**.go'
      - '**/go.mod'
      - '**/go.sum'

jobs:
  changelog:
    if: contains(github.event.pull_request.body, '[skip changelog]') == false &&
        contains(github.event.pull_request.labels.*.name, 'skip/changelog') == false &&
        github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    name: Changelog
    steps:
      - id: changelog
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ENDPOINT: repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files
          SELECTOR: 'map(select(.filename == "CHANGELOG.md")) | length'
        run: gh api "$ENDPOINT" --jq "$SELECTOR" | xargs -I{} echo "modified={}" | tee -a $GITHUB_OUTPUT
      - if: steps.changelog.outputs.modified == '0'
        env:
          MESSAGE: |
            docs/changelogs/ was not modified in this PR. Please do one of the options in [changelog management conventions](https://github.com/filecoin-project/lotus/blob/master/CONTRIBUTING.md#changelog-management)
        run: |
          echo "::error::${MESSAGE//$'\n'/%0A}"
          exit 1
