name: Create Release Issue

on:
  workflow_dispatch:
    inputs:
      type:
        description: "What's the type of the release?"
        required: true
        type: choice
        options:
          - node
          - miner
          - both
      tag:
        description: "What's the tag of the release? (e.g., 1.30.1)"
        required: true
      level:
        description: "What's the level of the release?"
        required: true
        default: 'patch'
        type: choice
        options:
          - minor
          - patch
      release-flow:
        description: "Which release flow should the issue use?"
        required: true
        default: 'auto'
        type: choice
        options:
          - auto
          - rc
          - no-rc
      network-upgrade:
        description: "What's the version of the network upgrade this release is related to? (e.g. 25)"
        required: false
      discussion-link:
        description: "What's a link to the GitHub Discussions topic for the network upgrade?"
        required: false
      changelog-link:
        description: "What's a link to the Lotus CHANGELOG entry for the network upgrade?"
        required: false
      rc1-date:
        description: "What's the expected shipping date for RC1? Ignored for no-RC releases."
        required: false
        default: "TBD"
      stable-date:
        description: "What's the expected shipping date for the stable release?"
        required: false
        default: "TBD"

defaults:
  run:
    shell: bash

permissions:
  contents: read
  issues: write

jobs:
  create-issue:
    name: Create Release Issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-go
      - env:
          GITHUB_TOKEN: ${{ github.token }}
          RELEASE_TYPE: ${{ github.event.inputs.type }}
          RELEASE_TAG: ${{ github.event.inputs.tag }}
          RELEASE_LEVEL: ${{ github.event.inputs.level }}
          RELEASE_FLOW: ${{ github.event.inputs.release-flow }}
          NETWORK_UPGRADE: ${{ github.event.inputs.network-upgrade }}
          DISCUSSION_LINK: ${{ github.event.inputs.discussion-link }}
          CHANGELOG_LINK: ${{ github.event.inputs.changelog-link }}
          RC1_DATE: ${{ github.event.inputs.rc1-date }}
          STABLE_DATE: ${{ github.event.inputs.stable-date }}
        run: |
          go run cmd/release/main.go create-issue \
            --create-on-github=true \
            --type "$RELEASE_TYPE" \
            --tag "$RELEASE_TAG" \
            --level "$RELEASE_LEVEL" \
            --release-flow "$RELEASE_FLOW" \
            --network-upgrade "$NETWORK_UPGRADE" \
            --discussion-link "$DISCUSSION_LINK" \
            --changelog-link "$CHANGELOG_LINK" \
            --rc1-date "$RC1_DATE" \
            --stable-date "$STABLE_DATE" \
            --repo "filecoin-project/lotus"
