name: Create Release Issue

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Release type'
        required: true
      tag:
        description: "What's the tag of the release? (e.g. 1.30.1)"
        required: true
      level:
        description: "What's the level of the release? (major, minor, patch)"
        required: true
      network-upgrade:
        description: "What's the version of the network upgrade this release is related to? (e.g. 23)"
        required: false
      discussion-link:
        description: "What's a link to the GitHub Discussions topic for the network upgrade?"
        required: false
      changelog-link:
        description: "What's a link to the Lotus CHANGELOG entry for the network upgrade?"
        required: false
      rc1-date:
        description: "What's the expected shipping date for RC1 (YYYY-MM-DD)?"
        required: false
      rc1-precision:
        description: "How precise is the RC1 date? (day, week)"
        required: false
      rc1-confidence:
        description: "How confident is the RC1 date? (estimated, confirmed)"
        required: false
      stable-date:
        description: "What's the expected shipping date for the stable release (YYYY-MM-DD)?"
        required: false
      stable-precision:
        description: "How precise is the stable release date? (day, week)"
        required: false
      stable-confidence:
        description: "How confident is the stable release date? (estimated, confirmed)"
        required: false

defaults:
  run:
    shell: bash

permissions:
  contents: read
  issues: write

jobs:
  create-issue:
    name: Create Release Issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-go
      - run: go build -o release ./cmd/release
      - env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ./release create-issue \
            --type "${{ github.event.inputs.type }}" \
            --tag "${{ github.event.inputs.tag }}" \
            --level "${{ github.event.inputs.level }}" \
            --network-upgrade "${{ github.event.inputs.network-upgrade }}" \
            --discussion-link "${{ github.event.inputs.discussion-link }}" \
            --changelog-link "${{ github.event.inputs.changelog-link }}" \
            --rc1-date "${{ github.event.inputs.rc1-date }}" \
            --rc1-precision "${{ github.event.inputs.rc1-precision }}" \
            --rc1-confidence "${{ github.event.inputs.rc1-confidence }}" \
            --stable-date "${{ github.event.inputs.stable-date }}" \
            --stable-precision "${{ github.event.inputs.stable-precision }}" \
            --stable-confidence "${{ github.event.inputs.stable-confidence }}"
