name: Comment with sorted PR checks

on:
  workflow_dispatch:
    inputs:
      pull_number:
        description: 'Pull request number'
        required: true
  workflow_run:
    workflows:
      - Build
      - Check
      - CodeQL
      - Test
    types:
      - requested
      - completed

permissions:
  actions: read
  checks: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.pull_number }}-${{ github.event.workflow_run.head_repository.full_name }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: false

jobs:
  comment:
    if: github.event.inputs.pull_number || github.event.workflow_run.event == 'pull_request'
    uses: ipdxco/sorted-pr-checks/.github/workflows/comment.yml@e93469d12abf23967b6346a76599e1a087161c82 # v2.0.0
    with:
      pull_number: ${{ github.event.inputs.pull_number }}
      template: unsuccessful_only
