name: Close and mark stale issue

on:
  schedule:
  - cron: '0 12 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Oops, seems like we needed more information for this issue, please comment with more details or this issue will be closed in 24 hours.'
        close-issue-message: 'This issue was closed because it is missing author input.'
        stale-pr-message: 'Thank you for submitting the PR and contributing to lotus! Lotus maintainers need more of your input before merging it, please address the suggested changes or reply to the comments or this PR will be closed in 48 hours. You are always more than welcome to reopen the PR later as well!'
        close-pr-message: 'This PR was closed because it is missing author input. Please feel free to reopen the PR when you get to it! Thank you for your interest in contributing to lotus!'
        stale-issue-label: 'kind/stale'
        stale-pr-label: 'kind/stale'
        any-of-labels: 'need/author-input '
        days-before-issue-stale: 3
        days-before-issue-close: 1
        days-before-pr-stale: 5
        days-before-pr-close: 2
        remove-stale-when-updated: true
        enable-statistics: true


