name: Close and mark stale issue

on:
  schedule:
  - cron: '0 12 * * *'

permissions:
  contents: read

jobs:
  planner:
    name: Detect docs-only changes
    runs-on: ubuntu-latest
    outputs:
      continue: ${{ steps.check.outputs.only_markdown_changes != 'true' }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Check for markdown-only changes
        id: check
        uses: ./.github/actions/only-markdown
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  stale:
    permissions:
      issues: write
      pull-requests: write
    needs: planner
    if: ${{ needs.planner.outputs.continue }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ github.token }}
        stale-issue-message: 'We needed more information for this issue, please comment with more details or this issue will be closed in 72 hours.'
        close-issue-message: 'This issue was closed because it is missing author input.'
        stale-pr-message: 'Thank you for submitting the PR and contributing to lotus! Lotus maintainers need more of your input before merging it, please address the suggested changes or reply to the comments or this PR will be closed in 72 hours. You are always more than welcome to reopen the PR later as well!'
        close-pr-message: 'This PR was closed because it is missing author input. Please feel free to reopen the PR when you get to it! Thank you for your interest in contributing to lotus!'
        stale-issue-label: 'kind/stale'
        stale-pr-label: 'kind/stale'
        any-of-labels: 'need/author-input '
        days-before-issue-stale: 3
        days-before-issue-close: 3
        days-before-pr-stale: 5
        days-before-pr-close: 3
        remove-stale-when-updated: true
        enable-statistics: true
