name: Repeat F3 Integration Tests

on:
  pull_request:

jobs:
  test:
    name: ${{ matrix.test }} ${{ matrix.go }}
    runs-on: ubuntu-latest
    #    needs: cache-test-bins
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.22
        test:
          - TestF3_Enabled
          - TestF3_Rebootstrap
          - TestF3_PauseAndRebootstrap
          - TestF3_Bootstrap
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: ./.github/actions/install-system-dependencies
      - uses: ./.github/actions/install-go
      - uses: ./.github/actions/make-deps
      - name: Repeat ${{ matrix.test }}
        run: go test -timeout 30m -count 50 -v --run='^${{ matrix.test }}' --failfast ./itests